### ISSUE TITLE
Get error when trying to run after install

### ISSUE THREAD

**Issue by lavinjj** [swirlycheetah/generator-angular2#14]
Following the directions, I've installed generator-angular2 globally, created a directory and try running yo angular2, but I get the following error:

Error: Cannot find module 'npm-check'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular2/app/index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I'm assuming there is some global dependency I need that isn't installed. I'm running on a Mac Book Pro using Node installed using brew.

**Comment by swirlycheetah** [comment]
Thanks for raising this, it looks like I mistakenly set npm-check as a development dependency which meant it wasn't being installed when installing the module.

I've amended that and pushed a new release ([0.1.4](https://github.com/swirlycheetah/generator-angular2/releases/tag/0.1.4)). You'll need to run `npm update -g generator-angular2` to pull the fix.

Any further issues or trouble be sure to let me know.
