### ISSUE TITLE
Problems with running application.

### ISSUE THREAD

**Issue by koodzik** [swirlycheetah/generator-angular2#25]
After generating app and running the server i saw this error.
```
GET http://localhost:8081/rx.js 404 (Not Found) (zone.js:535)
```
So i have added line in index.html
```
      System.config({
        paths: {
          'angular2/*': 'lib/angular2.js',
          'rx/dist/rx.all': 'lib/rx.all.js',
          'rx':  'lib/rx.all.js', // <--- 
          'index': 'index.js'
        }
      });
```

And now i have got different problem...
```
Error during instantiation of Token(AppComponentAnnotatedType)!. ORIGINAL ERROR: reflect-metadata shim is required when using class decorators

Error
    at InstantiationError.BaseException (angular2.js:8797)
    at InstantiationError.AbstractBindingError (angular2.js:20707)
    at new InstantiationError (angular2.js:20754)
    at _AsyncInjectorStrategy.execute._AsyncInjectorStrategy._findOrCreate (angular2.js:21094)
    at angular2.js:21074
    at Zone.run (zone.js:93)
    at zoneBoundFn (zone.js:70)
    at O (es6-module-loader.src.js:1177)
    at K (es6-module-loader.src.js:1136)
    at y.7.y.when (es6-module-loader.src.js:927)execute.BrowserDomAdapter.logError @ angular2.js:7299defaultErrorReporter @ angular2.js:6539execute.VmTurnZone._onError @ angular2.js:20289execute.VmTurnZone._createInnerZone.errorHandling.onError @ angular2.js:20258run @ zone.js:96zoneBoundFn @ zone.js:70O @ es6-module-loader.src.js:1177K @ es6-module-loader.src.js:11367.y.when @ es6-module-loader.src.js:9277.v.run @ es6-module-loader.src.js:8183.a._drain @ es6-module-loader.src.js:973.a.drain @ es6-module-loader.src.js:62b @ es6-module-loader.src.js:267
es6-module-loader.src.js:139 Potentially unhandled rejection [6] Error
    at InstantiationError.BaseException (http://localhost:8081/lib/angular2.js:8797:25)
    at InstantiationError.AbstractBindingError (http://localhost:8081/lib/angular2.js:20707:66)
    at new InstantiationError (http://localhost:8081/lib/angular2.js:20754:64)
    at _AsyncInjectorStrategy.execute._AsyncInjectorStrategy._findOrCreate (http://localhost:8081/lib/angular2.js:21094:21)
    at http://localhost:8081/lib/angular2.js:21074:27
    at Zone.run (http://localhost:8081/lib/zone.js:93:19)
    at zoneBoundFn (http://localhost:8081/lib/zone.js:70:19)
    at O (http://localhost:8081/lib/es6-module-loader.js:7:7462)
    at K (http://localhost:8081/lib/es6-module-loader.js:7:7094)
    at y.7.y.when (http://localhost:8081/lib/es6-module-loader.js:7:10248)
```

Chrome 42.

**Comment by swirlycheetah** [comment]
Thanks for reporting this. Apologies for the issues you're seeing, I'll take a look shortly.

**Comment by swirlycheetah** [comment]
It appears the latest alpha doesn't play nicely with this generator. I'll have to investigate that but for the time being I've pushed an update (`0.3.1`) with some changes @mrzepinski made, one of which targets specific alpha releases.

If you re-install the generator (`npm install -g generator-angular2`) things should be working again albeit against the previous alpha.

I'll create a new issue to look at getting things working with the latest alpha.
