### ISSUE TITLE
Error running yo angular2

### ISSUE THREAD

**Issue by tristanisfeld** [swirlycheetah/generator-angular2#28]
iojs v: 2.2.1
npm v: 2.11.0

$ yo angular2
module.js:334
    throw err;
          ^
Error: Cannot find module 'lru-cache'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at C:\Users\trist\AppData\Roaming\npm\node_modules\generator-angular2\node_modules\yeoman-generator\node_modules\download\node_modules\vinyl-fs\node_modules
\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch\minimatch.js:35:11
    at Object.<anonymous> (C:\Users\trist\AppData\Roaming\npm\node_modules\generator-angular2\node_modules\yeoman-generator\node_modules\download\node_modules\v
inyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch\minimatch.js:1051:3)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)

**Comment by tristanisfeld** [comment]
After uninstalling iojs and installing nodejs 0.12.4, the issue is resolved. This appears to be a iojs breaking change of yeoman generators.

**Comment by swirlycheetah** [comment]
Thanks for reporting, will keep an eye out for this in the future. Glad you got things working though!
